Разметка главной страницы
htmlacademy-adaptive/209004-mishka-25 pull request #2
Opened 2022-04-01 18:46 UTC by Zdravoles

2022-04-04 08:18 UTC, mikhin commented on source/index.html
> +        <img src="/img/mishka-logo-mobile.svg" width="85" height="34" alt="Слово Мишка латиницей">
Есть очень хорошая практика — размечать классами вообще весь HTML, даже если классы будут не нужны при стилизации. Большая польза будет в том, что код HTML становится более читабельным и более понятным, например, для твоих коллег-разработчиков.

2022-04-04 08:19 UTC, mikhin commented on source/index.html
> +        <img src="/img/mishka-logo-mobile.svg" width="85" height="34" alt="Слово Мишка латиницей">
крутой `alt`

2022-04-04 08:19 UTC, mikhin commented on source/index.html
> +          <li class="menu-main__item menu-main__item--search">
правильно используются модификаторы — вместе с основным классом, круто!

2022-04-04 08:20 UTC, mikhin commented on source/index.html
> +      <button class="page-header__toogle" type="button">
хорошо, что указываешь тип кнопки, многие про это забывают

2022-04-04 08:21 UTC, mikhin commented on source/index.html
> +      <section class="topic">
Классы, состоящие из одного слова, тяжело воспринимать и понимать. Хочется читать код, и не заглядывая при этом в стили и в макет, понимать о чем идет речь.

2022-04-04 08:23 UTC, mikhin commented on source/index.html
> +      <section class="topic">
Section — это не замена `div`, это тег, имеющий свой семантический смысл. Section — это именно _раздел_ контента, за которым пришел пользователь. Например, если на странице представлены рецепты для разных категорий, или представлены описания автозапчастей. Т.е. этот тег он именно отделяет независимые _большие_ части контента друг от друга.

2022-04-04 08:24 UTC, mikhin commented on source/index.html
> +      <section class="menu-catalog">
см. выше про section

2022-04-04 08:24 UTC, mikhin commented on source/index.html
> +        <h2><span class="visually-hidden">Разделы Каталога</span></h2>
`Каталога с маленькой буквы`

2022-04-04 08:26 UTC, mikhin commented on source/index.html
> +        <h2 class="product-week__title product__name">Вязаные корзинки</h2>
Это не формальная ошибка по БЭМ, но это большое практическое неудобство — почти никогда мы не должны хотеть смешивать в разметке два разных БЭМ-блока, т.к. блоки — это уникальные сущности, они могут быть и должны использоваться независимо друг от друга.

Сейчас, по смешению блоков в этом участке кода я не могу представить себе, как мне отдельно использовать `product-week` и `product`.

2022-04-04 08:26 UTC, mikhin commented on source/index.html
> +        <dl class="product__properties-list">
лайк за семантику

2022-04-04 08:26 UTC, mikhin commented on source/index.html
> +          <li class="advantages__item advantages__item--eco">Экологически чистые материалы</li>
а тут модификаторы прям уже точно нужны? если прям точно, то ок

2022-04-04 08:31 UTC, mikhin commented on source/index.html
> +      <section class="reviews slider">
см. коммент выше про смешение блоков

2022-04-04 08:31 UTC, mikhin commented on source/index.html
> +          <button class="reviews__toggle reviews__toggle--left slider__toogle slider__toogle--left" type="button">
`toogle` опечатка

2022-04-04 08:33 UTC, mikhin commented on source/index.html
> +          <button class="reviews__toggle reviews__toggle--left slider__toogle slider__toogle--left" type="button">
вот на этом смешении 4-х классов должна хорошо чувствоваться проблема — как твой коллега, я пока не очень понимаю как мне переиспользовать твой код в другой раз в другом случае: типа, что будет если я отдельно возьму блок `reviews` и как быть если я отдельно возьму блок `slider`?

2022-04-04 08:33 UTC, mikhin commented on source/index.html
> +    <template id="addBasketModal">
А зачем темплейт?

2022-04-04 08:35 UTC, mikhin requested changes
нужно немного доработать

2022-04-04 15:09 UTC, Zdravoles commented on source/index.html
> +        <h2 class="product-week__title product__name">Вязаные корзинки</h2>
можно, например, так использовать: 
появится блок "Товар дня" или "Рекомендуем" и туда можно будет вставлять данные товара, а сама секция по другому будет оформлена

у меня сейчас сделано так, что я могу выводить характеристики товара с помощью js, ориентируясь на элементы блока "product"

может сказывается, что перед этим курсом я прошёл курс по js 
то есть я использовал класс product больше для js

но согласен, что я забежал вперёд, и именно для вёрстки это лишний блок

2022-04-04 15:09 UTC, Zdravoles commented on source/index.html
> +          <li class="advantages__item advantages__item--eco">Экологически чистые материалы</li>
а как мне иконки разные применять к элементам списка?
можно по nth-child(n) , но я думал, так не по БЭМ
если есть ещё какой вариант, то подскажи, пожалуйста

2022-04-04 15:10 UTC, Zdravoles commented on source/index.html
> +    <template id="addBasketModal">
тоже для js

чтобы элемент создавать только, если потребуется

до курса по js делал такие вещи просто скрытым блоком

переделать?

2022-04-04 15:12 UTC, Zdravoles commented
в курсе нажал кнопку "обновить пулреквест"
надо нажимать кнопку "отправить повторно" или лучше подождать ответов на мои комментарии?

2022-04-05 17:15 UTC, mikhin commented on source/index.html
> +          <button class="reviews__toggle reviews__toggle--left slider__toogle slider__toogle--left" type="button">
@Zdravoles 

Существует такой подход, да — HTML и CSS живут своей дружной жизнью, а JS где-то сбоку, сам по себе, для него мы в разметке создадим отдельные классы. Мне такой подход не нравится, потому что в реальном более-менее среднем проекте по размеру, где у нас есть допустим 30-50 БЭМ-блоков и где полно интерактивности, JS становится сложным, непонятным, плохо читаемым и тяжело исправляемым, т.к. в таком подходе тяжело выстроить какую-либо систему и дальше следовать ей. Типа, — ой, ну классик пихнем сюда, классик добавим тут, пару классиков шмякнем здесь и потом как-то оживим в JS. Получается, что обмазали все какими-то рандомными классами, а через месяц уже сами забыли, чего мы там раньше делали.

Чтобы избежать этой проблемы, можно также следовать БЭМу, который говорит — неважно, какие технологии использует БЭМ-блок: HTML, CSS, JS или что угодно, что изобретут через 100 лет, — все файлы каждого независимого БЭМ-блока должны лежать в отдельной директории, и внутри себя реализовывать такой код, который полагается только на классы этого блока, и ни на какие другие. Таким образом у нас получается очень строгая понятная система, где ты сразу вынужден писать осознанный простой код, и где невозможно допустить грязное смешение разных сущностей.

Пример, где можно глянуть отдельные стили, разметку и JS для каждого БЭМ-блока:
- https://github.com/mikhin/kultura/tree/master/app/blocks/promo-carousel
- https://github.com/mikhin/kultura/blob/master/app/blocks/menu/menu.js

2022-04-05 17:16 UTC, mikhin commented on source/index.html
> +      <section class="reviews slider">
лучше убрать, да, отписал телегу ниже

2022-04-05 17:16 UTC, mikhin commented on source/index.html
> +          <li class="advantages__item advantages__item--eco">Экологически чистые материалы</li>
не, я и говорю, если прям точно нужны, то ок)

2022-04-05 17:17 UTC, mikhin commented on source/index.html
> +        <h2 class="product-week__title product__name">Вязаные корзинки</h2>
давай пока уберем, отписал телегу ниже

2022-04-05 17:17 UTC, merged

2022-04-05 17:32 UTC, Zdravoles commented on source/index.html
> +      <h1 class="page__main__topic page__main__topic--image">Милые штуки ручной работы для дома</h1>
я поправил в другом коммите на 
<main class="page-main">
      <h1 class="page-main__topic page-main__topic--image">Милые штуки ручной работы для дома</h1>
 
 такое название класса, как page-main нормально?

2022-04-05 17:35 UTC, Zdravoles commented on source/index.html
> +      <h1 class="page__main__topic page__main__topic--image">Милые штуки ручной работы для дома</h1>
проверка вставки кода в комментарий:
```
<main class="page-main">
      <h1 class="page-main__topic page-main__topic--image">Милые штуки ручной работы для дома</h1>
```

2022-04-05 17:36 UTC, Zdravoles commented on source/index.html
> +      <h1 class="page__main__topic page__main__topic--image">Милые штуки ручной работы для дома</h1>
получилось :)

вот такой класс нормально?

```
<main class="page-main">
      <h1 class="page-main__topic page-main__topic--image">Милые штуки ручной работы для дома</h1>
```