Разметка внутренних страниц
htmlacademy-adaptive/209004-mishka-25 pull request #3
Opened 2022-04-06 10:11 UTC by Zdravoles

2022-04-06 19:51 UTC, mikhin commented on source/catalog.html
> +        <h2>Зайчик-попрыгайчик</h2>
я бы бахнул класс

2022-04-06 19:52 UTC, mikhin commented on source/catalog.html
> +        <p class="process__text">По просьбам наших любимых фолловеров мы сняли для вас подробное видео о том, как появляются наши товары.</p>
почти никогда нет смысла называть что либо в верстке просто `text`, т.к. все что мы тут делаем — это текст =) чуть точнее будет назвать `description`

2022-04-06 19:53 UTC, mikhin commented on source/catalog.html
> +          <a href=""></a>
давай бахнем контент какой-нибудь?

2022-04-06 19:53 UTC, mikhin commented on source/catalog.html
> +      <a class="copyrights" href="https://htmlacademy.ru/intensive/adaptive">Разработано</a>
copyright

2022-04-06 19:53 UTC, mikhin commented on source/form.html
> +        <h2><span class="visually-hidden">Форма заказа</span></h2>
класс можно бахнуть прям на h2

2022-04-06 19:54 UTC, mikhin commented on source/form.html
> +            <label class="order__one-select">
one-select > radio

2022-04-06 19:54 UTC, mikhin commented on source/form.html
> +        <form class="order__form" method="POST" action="https://echo.htmlacademy.ru">
я бы вынес форму в отдельный бэм-блок, т.к. форма может быть использована не только для заказа, но и например для обратной связи

2022-04-06 19:54 UTC, mikhin commented on source/form.html
> +            <legend class="order__title-section">Тип</legend>
__title-section – не очень понятно о чем речь

2022-04-06 19:55 UTC, mikhin commented on source/form.html
> +              <input type="radio" name="interier" checked>
interior

2022-04-06 19:56 UTC, mikhin commented on source/form.html
> +            <label class="order__select">
по идее не должны хотеть дублировать стили в разных классах для лейблов, т.к. они одинаковы по дизайну, а значит это один и тот же элемент

2022-04-06 19:57 UTC, mikhin commented on source/form.html
> +            <label class="order__label" for="fioName">Имя:</label>
я бы подумал в сторону того, чтобы у всех лейблов было одинаковое название, а разницу в дизайне можно выразить через модификаторы

2022-04-06 19:58 UTC, mikhin commented on source/form.html
> +
лишние пустые строки

2022-04-06 19:59 UTC, mikhin requested changes
нужно немного поправить

2022-04-07 07:18 UTC, Zdravoles commented on source/form.html
> +
это для лучшего чтения кода
но убрал

2022-04-07 07:22 UTC, Zdravoles commented
правки сделал

2022-04-07 08:15 UTC, mikhin commented on source/form.html
> +            <legend class="order-form__title-partition">Фио</legend>
лучше так и написать __legend, а то не понятно что такое `title-partition`

2022-04-07 08:16 UTC, merged