Адаптивная сетка для главной страницы
htmlacademy-adaptive/209004-mishka-25 pull request #5
Opened 2022-04-28 10:44 UTC by Zdravoles

2022-04-29 08:41 UTC, mikhin requested changes

2022-04-29 08:41 UTC, mikhin commented on source/catalog.html
> +            <button class="button button__default" type="button">Сделать заказ</button>
Один узел не может быть и блоком и элементом. Если это модификатор, то нотация в нейминге должна быть другая.

2022-04-29 08:41 UTC, mikhin commented on source/index.html
> +          <li class="menu-main__item menu-main__item--catalog">
А зачем модификаторы на каждый пункт?

2022-04-29 08:41 UTC, mikhin commented on source/index.html
> +            <a class="menu-main__link menu-main__link--delivery" href="/delivery/">
есть хороший прием который позволяет сократить количество лишних модификаторов в разметке — селектор вложенности элементов

``` css
.menu-main__item--delivery {
  & .menu-main__link {
    something
  }
}
```

2022-04-29 08:41 UTC, mikhin commented on source/index.html
> +      <a class="logo logo__footer" aria-label="Логотип Мишка"></a>
Тоже самое — не может две сущности одного блока висеть на одном узле.

2022-04-29 08:41 UTC, mikhin commented on source/less/blocks/menu-main.less
> +  position: absolute;
На бэм-блоках запрещены любые правила "внешней геометрии".

2022-04-29 08:41 UTC, mikhin commented on source/less/blocks/menu-main.less
> +  @media (min-width: @tablet-width) {
медиа для элемента должны идти выше чем before, т.к. они относятся к селектору, а бефор это уже как будто следующий элемент

2022-04-29 08:41 UTC, mikhin commented on source/less/blocks/menu-main.less
> +      width: 100%;
селектор медиа нужно перенести внутрь before

2022-05-01 10:11 UTC, Zdravoles commented on source/index.html
> +          <li class="menu-main__item menu-main__item--catalog">
для того, чтобы прописать grid-area для последующей перестройки расположения элементов

2022-05-01 20:08 UTC, mikhin requested changes

2022-05-01 20:08 UTC, mikhin commented on source/index.html
> +      <nav class="menu-main menu-main--wrapper visually-hiddens">
Непонятный модификатор. Что значит модификация `wrapper` в контексте смысла `menu-main`?

2022-05-01 20:08 UTC, mikhin commented on source/less/blocks/menu-main.less
> +.menu-main--wrapper {
Это модификатор блока, к нему применяются все те же правила, что и к блоку, а значит тоже нельзя вешать геометрию.

2022-05-01 20:08 UTC, mikhin commented on source/index.html
> +      <nav class="menu-main menu-main--wrapper visually-hiddens">
Если мы хотим его спозиционировать, мы можем примиксовать к нему сущность элемента от другого бэм-блока, который находится выше по дереву.

2022-05-01 20:08 UTC, mikhin commented on source/less/blocks/menu-main.less
>    @media (min-width: @tablet-width) {
Медиа для `.menu-main__item--delivery` должны идти выше чем `& .menu-main__link`

2022-05-02 10:45 UTC, mikhin approved these changes

2022-05-02 10:45 UTC, merged